### ISSUE TITLE
ADD 1.14.X SUPPORT

### ISSUE THREAD

**Issue by successed** [ThePhilderbeast/AutoPickup#19]
[19:06:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'autopickup' in plugin AutoPickup v5.1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1832) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1640) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:976) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-86]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getName()Ljava/lang/String;
        at me.MnMaxon.AutoPickup.commands.Common.openGui(Common.java:184) ~[?:?]
        at me.MnMaxon.AutoPickup.commands.AutoPickup.onCommand(AutoPickup.java:20) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.2.jar:git-Paper-86]
        ... 17 more

**Comment by successed** [comment]
[19:07:16 ERROR]: Could not pass event InventoryClickEvent to AutoPickup v5.1.0
java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
        at me.MnMaxon.AutoPickup.listners.MainListener.onInvClick(MainListener.java:90) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor867.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-86]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2342) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:976) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-86]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
