### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by VictorAlonsoo** [ThePhilderbeast/AutoPickup#25]
`[Pterodactyl Daemon] Your server is sending too much data too quickly! Automatic spam detection triggered.
>.... [03:33:53 ERROR]: Could not pass event ItemSpawnEvent to AutoPickup v5.2.3
java.lang.StackOverflowError: null
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftItem.<init>(CraftItem.java:20) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftItem.<init>(CraftItem.java:25) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.getEntity(CraftEntity.java:354) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.Entity.getBukkitEntity(Entity.java:84) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:636) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:536) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:1002) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:924) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.dropItem(CraftWorld.java:685) ~[patched_1.14.4.jar:git-Paper-152]
at me.MnMaxon.AutoPickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
at me.MnMaxon.AutoPickup.actions.LocationActions.doAutoActions(LocationActions.java:76) ~[?:?]
at me.MnMaxon.AutoPickup.listners.MainListener.onItemSpawn(MainListener.java:307) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor75.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-152]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:641) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:536) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:1002) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:924) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.dropItem(CraftWorld.java:685) ~[patched_1.14.4.jar:git-Paper-152]
at me.MnMaxon.AutoPickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
at me.MnMaxon.AutoPickup.actions.LocationActions.doAutoActions(LocationActions.java:76) ~[?:?]
at me.MnMaxon.AutoPickup.listners.MainListener.onItemSpawn(MainListener.java:307) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor75.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-152]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:641) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:536) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:1002) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:924) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.dropItem(CraftWorld.java:685) ~[patched_1.14.4.jar:git-Paper-152]
at me.MnMaxon.AutoPickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
at me.MnMaxon.AutoPickup.actions.LocationActions.doAutoActions(LocationActions.java:76) ~[?:?]
at me.MnMaxon.AutoPickup.listners.MainListener.onItemSpawn(MainListener.java:307) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor75.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-152]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:641) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:536) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:1002) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:924) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.dropItem(CraftWorld.java:685) ~[patched_1.14.4.jar:git-Paper-152]
at me.MnMaxon.AutoPickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
at me.MnMaxon.AutoPickup.actions.LocationActions.doAutoActions(LocationActions.java:76) ~[?:?]
at me.MnMaxon.AutoPickup.listners.MainListener.onItemSpawn(MainListener.java:307) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor75.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-152]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:641) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:536) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:1002) ~[patched_1.14.4.jar:git-Paper-152]
at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:924) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.dropItem(CraftWorld.java:685) ~[patched_1.14.4.jar:git-Paper-152]
at me.MnMaxon.AutoPickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
at me.MnMaxon.AutoPickup.actions.LocationActions.doAutoActions(LocationActions.java:76) ~[?:?]
at me.MnMaxon.AutoPickup.listners.MainListener.onItemSpawn(MainListener.java:307) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor75.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-152]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:641) ~[patched_1.14.4.jar:git-Paper-152]`

**Comment by ThePhilderbeast** [comment]
the com.destroystokyo.paper plugin is doing something strange thats not compatible. looking at that but with no context its hard to tell.
