### ISSUE TITLE
Console error problem

### ISSUE THREAD

**Issue by successed** [ThePhilderbeast/AutoPickup#44]
FİX THİS PROBLEM
``
        at me.MnMaxon.AutoPickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
        at me.MnMaxon.AutoPickup.actions.LocationActions.doAutoActions(LocationActions.java:76) ~[?:?]
        at me.MnMaxon.AutoPickup.listners.MainListener.onItemSpawn(MainListener.java:307) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor226.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-32]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:653) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:548) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1169) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1077) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.dropItem(CraftWorld.java:704) ~[patched_1.15.1.jar:git-Paper-32]
        at me.MnMaxon.AutoPickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
        at me.MnMaxon.AutoPickup.actions.LocationActions.doAutoActions(LocationActions.java:76) ~[?:?]
        at me.MnMaxon.AutoPickup.listners.MainListener.onItemSpawn(MainListener.java:307) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor226.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-32]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:653) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:548) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1169) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1077) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.dropItem(CraftWorld.java:704) ~[patched_1.15.1.jar:git-Paper-32]
        at me.MnMaxon.AutoPickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
        at me.MnMaxon.AutoPickup.actions.LocationActions.doAutoActions(LocationActions.java:76) ~[?:?]
        at me.MnMaxon.AutoPickup.listners.MainListener.onItemSpawn(MainListener.java:307) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor226.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-32]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:653) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:548) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1169) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1077) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.dropItem(CraftWorld.java:704) ~[patched_1.15.1.jar:git-Paper-32]
        at me.MnMaxon.AutoPickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
        at me.MnMaxon.AutoPickup.actions.LocationActions.doAutoActions(LocationActions.java:76) ~[?:?]
        at me.MnMaxon.AutoPickup.listners.MainListener.onItemSpawn(MainListener.java:307) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor226.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-32]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:653) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:548) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1169) ~[patched_1.15.1.jar:git-Paper-32]

``

**Comment by ThePhilderbeast** [comment]
1.15 is not supported yet, and neither is paper spiggot, your on your own with this one sorry

**Comment by successed** [comment]
> 1.15 is not supported yet, and neither is paper spiggot, your on your own with this one sorry

Just update plugin.

**Comment by ThePhilderbeast** [comment]
its not that simple, an update of version takes a huge amount of work, it will be done when its done, and only if/when i get the time.

and even when the update is done, Paper spigot will remain unsupported.
