### ISSUE TITLE
update 1.15.1

### ISSUE THREAD

**Issue by successed** [ThePhilderbeast/AutoPickup#45]
Can you add 1.15.1 support please ?

**Comment by ThePhilderbeast** [comment]
beta release is published

**Comment by successed** [comment]
i setup my server 1.15.1, i'am waiting 1.15.1 relase

**Comment by ThePhilderbeast** [comment]
a full release is probably a week or 2 away at least

**Comment by successed** [comment]
> a full release is probably a week or 2 away at least

`[20:35:14] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to AutoPickup v{{version=null}=null}
java.lang.StackOverflowError: null
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftItem.<init>(CraftItem.java:20) ~[patched_1.15.1.jar:git-Paper-50]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftItem.<init>(CraftItem.java:25) ~[patched_1.15.1.jar:git-Paper-50]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.getEntity(CraftEntity.java:356) ~[patched_1.15.1.jar:git-Paper-50]
	at net.minecraft.server.v1_15_R1.Entity.getBukkitEntity(Entity.java:85) ~[patched_1.15.1.jar:git-Paper-50]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:649) ~[patched_1.15.1.jar:git-Paper-50]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:549) ~[patched_1.15.1.jar:git-Paper-50]
	at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1178) ~[patched_1.15.1.jar:git-Paper-50]
	at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1086) ~[patched_1.15.1.jar:git-Paper-50]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.dropItem(CraftWorld.java:703) ~[patched_1.15.1.jar:git-Paper-50]
	at com.philderbeast.autopickup.actions.AutoPickup.pickup(AutoPickup.java:65) ~[?:?]
	at com.philderbeast.autopickup.actions.LocationActions.doAutoActions(LocationActions.java:75) ~[?:?]`

**Comment by ThePhilderbeast** [comment]
paper spigot will still not be supported in 1.15, please don't post logs from it.

**Comment by successed** [comment]
> paper spigot will still not be supported in 1.15, please don't post logs from it.

Just support.

**Comment by ThePhilderbeast** [comment]
its not as simple as "just support"

your welcome to do the testing and support paper spigot yourself if you want the support that badly.
