### ISSUE TITLE
Lapis Auto Block

### ISSUE THREAD

**Issue by lilsketchy** [ThePhilderbeast/AutoPickup#74]
Error on startup:
```
[15:57:25 ERROR]: Failed to load all configs, using defaults
[15:57:25 ERROR]: Error occurred while enabling AutoPickup v5.4.0 (Is it up to date?)
java.lang.NoSuchFieldError: LAPIS_LAZULI
        at com.philderbeast.autopickup.actions.AutoBlock.<clinit>(AutoBlock.java:209) ~[?:?]
        at com.philderbeast.autopickup.Config.reloadConfigs(Config.java:110) ~[?:?]
        at com.philderbeast.autopickup.AutoPickupPlugin.onEnable(AutoPickupPlugin.java:51) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:315) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:321) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:280) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:460) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:422) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:326) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:273) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[15:57:25 INFO]: [AutoPickup] Disabling AutoPickup v5.4.0
```

**Comment by ThePhilderbeast** [comment]
minecraft 1.8 is no longer supported.

5.4.0 only support 1.16+
